name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
[![Validate 'setup-go'](https://github.com/https-githubsup-com/setup-go/actions/workflows/versions.yml/badge.svg)](https://github.com/https-githubsup-com/setup-go/actions/workflows/versions.yml)
